---
title: "wordle"
author: "Amber"
date: "2024-02-12"
output: html_document
---

## PRELIMINARIES

Load in Modules and data

```
{r}
collins <- read.table("https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/collins-scrabble-words-2019.txt", header=TRUE)
google <- read.table("https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/google-10000-english-usa-no-swears.txt", header=TRUE)
```

## STEP ONE

Creating a function called load_dictionary() that takes a single argument, "filename", that can be used to read in either of the two data files just downloaded. 

```
{r}
load_dictionary <- function(fileurl) {
      read.table(fileurl, header=TRUE)
}
```

Use function to create solution_list and valid_list 

```
{r}
valid_list <- load_dictionary("https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/collins-scrabble-words-2019.txt")
solution_list <- load_dictionary("https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/google-10000-english-usa-no-swears.txt")
```
Then just a quick test of the lists to confirm they worked:
```
{r}
str(valid_list)
str(solution_list)
```

## STEP TWO

Filtering the solution_list to only include words in the valid_list using intersect. 

```
{r}
solution_list <- inner_join (solution_list, valid_list)
```

## STEP THREE
This function does a few things: removes solutions from d that are not 5 letters in length, then chooses a word, then splits it into a vector of single-character elements

```
{r}
pick_solution <- function(list) {
      possible_answers <- filter (list, nchar (words) == 5)
      answers <- sample_n (possible_answers, 1, replace= FALSE)
      answer_split <- strsplit (answers$word,"") [[1]]
}
```
Now we run the function to see if it works:

```
{r}
solution <- pick_solution (solution_list)
```

## STEP FOUR

Time to actually play! I did have to use some help from online for this function, but did the bulk myself. 

```
{r}
evaluate_guess <- function (guess_vec, solution) {
  word_length <- length(solution)
  guess_res <- rep("-", word_length)

for (i in 1:word_length) {
  if (guess_vec[i] == solution[i]) {
    guess_res[i] <- "G" }
  else {
  guess_res[i] <- "-"
  }
}

for (i in 1:word_length) {
  if (guess_res[i] !="G") {
    idx <- match(guess_vec[i], solution)
  if (!is.na(idx)) {
    guess_res [i] <- "Y"
    solution [idx] <- "-"
    }
  }
}
return(guess_res)
}
```

This is the main function used to play wordle that uses the above function to evaluate. 

```
{r}
play_wordle <- function(solution, valid_list, num_guesses=6){
  print(paste("You have", num_guesses, "chances to guess a word of 5 letters"))
  guesses <- 0
  letters_rem <- LETTERS

while (guesses < num_guesses) {
  print(paste(c("Letters remaining:", letters_rem)))
  guesses <- guesses + 1
  guess <-readline ("Enter guess of 5 letters:")

guess <- toupper(guess)
guess_vec <- strsplit (guess,"") [[1]]

guess_res <- evaluate_guess(guess_vec, solution)

letters_rem <- setdiff(letters_rem, guess_vec)

print(paste(strsplit(guess,"")[[1]]))
print(paste(guess_res))

if (str_flatten(guess_res) == "GGGGG") {
  print ("You win!!")
  return (guesses)
  }
}

print(paste("Sorry, you lost! Answer was", str_flatten(solution)))
  return (guesses)
}
```

to play the game, copy this code into your r-studio console!
```play_wordle (solution, valid_list)```

Have fun!